./esc.sh tests/self/hello.es
/work/tamarin/bin/shell tests/self/hello.es.abc
./esc1.sh tests/self/if.es
/work/tamarin/bin/shell tests/self/if.es.abc
./esc.sh tests/self/for.es
/work/tamarin/bin/shell tests/self/for.es.abc
./esc.sh tests/self/try.es
/work/tamarin/bin/shell tests/self/try.es.abc
./esc.sh tests/self/cls.es
/work/tamarin/bin/shell tests/self/cls.es.abc
./esc.sh tests/self/switch.es
/work/tamarin/bin/shell tests/self/switch.es.abc
./esc.sh tests/self/switchtype.es
/work/tamarin/bin/shell tests/self/switchtype.es.abc
