1,
1.23,
null,
true,
false,
"string",
[0, true, "blue"] : [int, Boolean, String],
//[1, 2, "foo"] : Array,
//[1, 2, "bar"] : *,
//[1, 2, "baz"] : Object,
[1, 2, "foo"],
//{} : {},
//{} : *,
//{},
//{ x: 0, y: true, z: "blue" } : { x: int, y: Boolean },
//{ x: 0, y: true, z: "blue" } : { x: int, y: Boolean, z: String },
let (x=1) x
