#./esc1-t.sh debug.es
./esc1-t.sh util.es
#./esc1-t.sh lex-char.es
#./esc1-t.sh lex-token.es
#./esc1-t.sh lex-scan.es
#./esc1-t.sh ast.es
#./esc1-t.sh parse-util.es
#./esc1-t.sh parse-ident.es
#./esc1-t.sh parse-lhsexpr.es
#./esc1-t.sh parse-assignexpr.es
#./esc1-t.sh parse-ptrn.es
#./esc1-t.sh parse-type.es
#./esc1-t.sh parse-stmt.es
#./esc1-t.sh parse-defn.es
#./esc1-t.sh parse-prgm.es
#./esc1-t.sh decoder.es
#./esc1-t.sh encoder.es
#./esc1-t.sh util-tamarin.es
#./esc1-t.sh esc1-t.es

#./esc3-r.sh debug.es
#./esc3-r.sh util.es
#./esc3-r.sh ast.es
#./esc3-r.sh lex-char.es
#./esc3-r.sh lex-token.es
#./esc3-r.sh lex-scan.es
#./esc3-r.sh parse-util.es
#./esc3-r.sh parse-ident.es
#./esc3-r.sh parse-lhsexpr.es
#./esc3-r.sh parse-assignexpr.es
#./esc3-r.sh parse-ptrn.es
#./esc3-r.sh parse-type.es
#./esc3-r.sh parse-stmt.es
#./esc3-r.sh parse-defn.es
#./esc3-r.sh parse-prgm.es
#./esc3-r.sh decoder.es
#./esc3-r.sh encoder.es
#./esc3-r.sh util-tamarin.es
#./esc3-r.sh esc1-t.es
